### ISSUE TITLE
Zignatures app is unexpectedly hidden in the sidebar (in Chrome only; works fine in Edge)

### ISSUE THREAD

**Issue by jelkini4** [zendesklabs/zignatures#21]
Using Google Chrome Version 91.0.4472.106 (Official Build) (64-bit), the Zignatures app is unexpectedly hidden in the sidebar:
![Hidden](https://user-images.githubusercontent.com/90713488/133296388-4c8bf3b0-7f34-418c-887c-3b3e4e8d5b6d.png)

It works as expected in Microsoft Edge Version 92.0.902.67 (Official build) (64-bit):
![It works in Edge](https://user-images.githubusercontent.com/90713488/133296463-5bfb79d2-85c8-4d27-b7cf-999c9339a0ee.png)

Not sure if it's related, but I and my colleagues have other noticed problems with Zendesk apps and other UI features in Chrome that don't occur in Edge. For example, the TeamViewer app in Zendesk doesn't work properly in Chrome (it says "Loading..." forever), but it does work in Edge.
![TV App](https://user-images.githubusercontent.com/90713488/133296729-bcffe43b-d589-4d31-8679-a44e5b2eef45.gif)

My Environment:
Edition	Windows 10 Enterprise
Version	20H2
Installed on	‎8/‎29/‎2021
OS build	19042.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

**Comment by Sarapulov** [comment]
Thanks for reporting this.
I've seen such reports earlier. But it often been solved by cleaning cache & cookies.
Let me know if that helps?

**Comment by jelkini4** [comment]
That didn't seem to fix the problem. Would it help if I record the page loading in Dev Tools and send you the .HAR file?

**Comment by Sarapulov** [comment]
Hi,
you can send the HAR file.
But from what I've seen in the past this issue is irrelevant to the App. It works well to me and a number of other customers. So this is very likely the local issue. If so, not much I'll be able to do.

**Comment by Sarapulov** [comment]
The way you shared the file requires creating an account at Microsoft.
I prefer not to do so.
Can you share it here instead?

**Comment by jelkini4** [comment]
Sure, here you go:
[i4-insight.zendesk.com.har.zip](https://github.com/zendesklabs/zignatures/files/7199305/i4-insight.zendesk.com.har.zip)

**Comment by Sarapulov** [comment]
thanks.
I looked into the HAR file and it doesn't tell me much.
The issue reported here seems to be very local. Otherwise, I would have a number of other reports. That is not the case at this moment. 
If the App works on all other browsers and environments meaning there is nothing wrong with the code itself. In such cases there is not much I can recommend apart from common troubleshooting steps:
cleaning cookies & cache
checking if other installed apps are causing issues
checking if browser settings or extensions may cause the issue
do you have other apps working without any issues or is it just Zignatures?
